/**
 * Auto-generated Guild path mapping
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-schema.ts
 */

export interface PathMap {
  [path: string]: {
    field: string;
    children?: string[];
  };
}

export const GuildPathMap: PathMap = {
  "settings.prefix": {
    field: "prefix",
  },
  "settings.language": {
    field: "language",
  },
  "utils.join_to_create.enabled": {
    field: "jtcEnabled",
  },
  "utils.join_to_create.channel": {
    field: "jtcChannel",
  },
  "utils.join_to_create.category": {
    field: "jtcCategory",
  },
  "utils.join_to_create.default_name": {
    field: "jtcDefaultName",
  },
  "utils.counter.enabled": {
    field: "counterEnabled",
  },
  "utils.counter.category": {
    field: "counterCategory",
  },
  "utils.counter.channels": {
    field: "counterChannels",
  },
  "utils.levels.enabled": {
    field: "levelsEnabled",
  },
  "utils.levels.ignore_channels": {
    field: "levelsIgnoreChannels",
  },
  "utils.levels.ignore_roles": {
    field: "levelsIgnoreRoles",
  },
  "utils.levels.level_roles": {
    field: "levelsRoles",
  },
  "utils.levels.message.enabled": {
    field: "levelsMessageEnabled",
  },
  "utils.levels.message.channel": {
    field: "levelsMessageChannel",
  },
  "utils.levels.message.content": {
    field: "levelsMessageContent",
  },
  "utils.levels.message.delete": {
    field: "levelsMessageDelete",
  },
  "utils.find_team.enabled": {
    field: "findTeamEnabled",
  },
  "utils.find_team.channel": {
    field: "findTeamChannel",
  },
  "utils.find_team.send_channel": {
    field: "findTeamSendChannel",
  },
  "utils.find_team.games": {
    field: "findTeamGames",
  },
  "utils.components.modals": {
    field: "customModals",
  },
  "utils.components.embed": {
    field: "customEmbeds",
  },
  "utils.components.buttons": {
    field: "customButtons",
  },
  "utils.giveaways": {
    field: "giveaways",
  },
  "economy.currency.emoji": {
    field: "currencyEmoji",
  },
  "economy.currency.id": {
    field: "currencyId",
  },
  "economy.shop.roles": {
    field: "shopRoles",
  },
  "economy.income.work.enabled": {
    field: "workEnabled",
  },
  "economy.income.work.cooldown": {
    field: "workCooldown",
  },
  "economy.income.work.min": {
    field: "workMin",
  },
  "economy.income.work.max": {
    field: "workMax",
  },
  "economy.income.timely.enabled": {
    field: "timelyEnabled",
  },
  "economy.income.timely.amount": {
    field: "timelyAmount",
  },
  "economy.income.daily.enabled": {
    field: "dailyEnabled",
  },
  "economy.income.daily.amount": {
    field: "dailyAmount",
  },
  "economy.income.weekly.enabled": {
    field: "weeklyEnabled",
  },
  "economy.income.weekly.amount": {
    field: "weeklyAmount",
  },
  "economy.income.level_up.enabled": {
    field: "levelUpEnabled",
  },
  "economy.income.level_up.amount": {
    field: "levelUpAmount",
  },
  "economy.income.bump.enabled": {
    field: "bumpEnabled",
  },
  "economy.income.bump.amount": {
    field: "bumpAmount",
  },
  "economy.income.rob.enabled": {
    field: "robEnabled",
  },
  "economy.income.rob.cooldown": {
    field: "robCooldown",
  },
  "economy.income.rob.income": {
    field: "robIncome",
  },
  "economy.income.rob.punishment": {
    field: "robPunishment",
  },
  "moderation.moderation_roles": {
    field: "moderationRoles",
  },
  "moderation.auto_moderation.invite.enabled": {
    field: "inviteEnabled",
  },
  "moderation.auto_moderation.invite.ignore_channels": {
    field: "inviteIgnoreChannels",
  },
  "moderation.auto_moderation.invite.ignore_roles": {
    field: "inviteIgnoreRoles",
  },
  "moderation.auto_moderation.invite.delete_message": {
    field: "inviteDeleteMessage",
  },
  "moderation.auto_moderation.invite.moderation_immune": {
    field: "inviteModerationImmune",
  },
  "moderation.auto_moderation.invite.punishment": {
    field: "invitePunishment",
  },
  "moderation.auto_moderation.links.enabled": {
    field: "linksEnabled",
  },
  "moderation.auto_moderation.links.ignore_channels": {
    field: "linksIgnoreChannels",
  },
  "moderation.auto_moderation.links.ignore_roles": {
    field: "linksIgnoreRoles",
  },
  "moderation.auto_moderation.links.ignore_links": {
    field: "linksIgnoreLinks",
  },
  "moderation.auto_moderation.links.delete_message": {
    field: "linksDeleteMessage",
  },
  "moderation.auto_moderation.links.moderation_immune": {
    field: "linksModerationImmune",
  },
  "moderation.auto_moderation.links.punishment": {
    field: "linksPunishment",
  },
  "permissions.commands": {
    field: "commandPermissions",
  },
  settings: {
    field: "",
    children: ["prefix", "language"],
  },
  utils: {
    field: "",
    children: ["giveaways"],
  },
  "utils.join_to_create": {
    field: "",
    children: ["enabled", "channel", "category", "default_name"],
  },
  "utils.counter": {
    field: "",
    children: ["enabled", "category", "channels"],
  },
  "utils.levels": {
    field: "",
    children: ["enabled", "ignore_channels", "ignore_roles", "level_roles"],
  },
  "utils.levels.message": {
    field: "",
    children: ["enabled", "channel", "content", "delete"],
  },
  "utils.find_team": {
    field: "",
    children: ["enabled", "channel", "send_channel", "games"],
  },
  "utils.components": {
    field: "",
    children: ["modals", "embed", "buttons"],
  },
  "economy.currency": {
    field: "",
    children: ["emoji", "id"],
  },
  "economy.shop": {
    field: "",
    children: ["roles"],
  },
  "economy.income.work": {
    field: "",
    children: ["enabled", "cooldown", "min", "max"],
  },
  "economy.income.timely": {
    field: "",
    children: ["enabled", "amount"],
  },
  "economy.income.daily": {
    field: "",
    children: ["enabled", "amount"],
  },
  "economy.income.weekly": {
    field: "",
    children: ["enabled", "amount"],
  },
  "economy.income.level_up": {
    field: "",
    children: ["enabled", "amount"],
  },
  "economy.income.bump": {
    field: "",
    children: ["enabled", "amount"],
  },
  "economy.income.rob": {
    field: "",
    children: ["enabled", "cooldown", "income", "punishment"],
  },
  moderation: {
    field: "",
    children: ["moderation_roles"],
  },
  "moderation.auto_moderation.invite": {
    field: "",
    children: [
      "enabled",
      "ignore_channels",
      "ignore_roles",
      "delete_message",
      "moderation_immune",
      "punishment",
    ],
  },
  "moderation.auto_moderation.links": {
    field: "",
    children: [
      "enabled",
      "ignore_channels",
      "ignore_roles",
      "ignore_links",
      "delete_message",
      "moderation_immune",
      "punishment",
    ],
  },
  permissions: {
    field: "",
    children: ["commands"],
  },
};

export const GuildFieldMap: Record<string, string> = {
  "settings.prefix": "prefix",
  "settings.language": "language",
  "utils.join_to_create.enabled": "jtcEnabled",
  "utils.join_to_create.channel": "jtcChannel",
  "utils.join_to_create.category": "jtcCategory",
  "utils.join_to_create.default_name": "jtcDefaultName",
  "utils.counter.enabled": "counterEnabled",
  "utils.counter.category": "counterCategory",
  "utils.counter.channels": "counterChannels",
  "utils.levels.enabled": "levelsEnabled",
  "utils.levels.ignore_channels": "levelsIgnoreChannels",
  "utils.levels.ignore_roles": "levelsIgnoreRoles",
  "utils.levels.level_roles": "levelsRoles",
  "utils.levels.message.enabled": "levelsMessageEnabled",
  "utils.levels.message.channel": "levelsMessageChannel",
  "utils.levels.message.content": "levelsMessageContent",
  "utils.levels.message.delete": "levelsMessageDelete",
  "utils.find_team.enabled": "findTeamEnabled",
  "utils.find_team.channel": "findTeamChannel",
  "utils.find_team.send_channel": "findTeamSendChannel",
  "utils.find_team.games": "findTeamGames",
  "utils.components.modals": "customModals",
  "utils.components.embed": "customEmbeds",
  "utils.components.buttons": "customButtons",
  "utils.giveaways": "giveaways",
  "economy.currency.emoji": "currencyEmoji",
  "economy.currency.id": "currencyId",
  "economy.shop.roles": "shopRoles",
  "economy.income.work.enabled": "workEnabled",
  "economy.income.work.cooldown": "workCooldown",
  "economy.income.work.min": "workMin",
  "economy.income.work.max": "workMax",
  "economy.income.timely.enabled": "timelyEnabled",
  "economy.income.timely.amount": "timelyAmount",
  "economy.income.daily.enabled": "dailyEnabled",
  "economy.income.daily.amount": "dailyAmount",
  "economy.income.weekly.enabled": "weeklyEnabled",
  "economy.income.weekly.amount": "weeklyAmount",
  "economy.income.level_up.enabled": "levelUpEnabled",
  "economy.income.level_up.amount": "levelUpAmount",
  "economy.income.bump.enabled": "bumpEnabled",
  "economy.income.bump.amount": "bumpAmount",
  "economy.income.rob.enabled": "robEnabled",
  "economy.income.rob.cooldown": "robCooldown",
  "economy.income.rob.income": "robIncome",
  "economy.income.rob.punishment": "robPunishment",
  "moderation.moderation_roles": "moderationRoles",
  "moderation.auto_moderation.invite.enabled": "inviteEnabled",
  "moderation.auto_moderation.invite.ignore_channels": "inviteIgnoreChannels",
  "moderation.auto_moderation.invite.ignore_roles": "inviteIgnoreRoles",
  "moderation.auto_moderation.invite.delete_message": "inviteDeleteMessage",
  "moderation.auto_moderation.invite.moderation_immune": "inviteModerationImmune",
  "moderation.auto_moderation.invite.punishment": "invitePunishment",
  "moderation.auto_moderation.links.enabled": "linksEnabled",
  "moderation.auto_moderation.links.ignore_channels": "linksIgnoreChannels",
  "moderation.auto_moderation.links.ignore_roles": "linksIgnoreRoles",
  "moderation.auto_moderation.links.ignore_links": "linksIgnoreLinks",
  "moderation.auto_moderation.links.delete_message": "linksDeleteMessage",
  "moderation.auto_moderation.links.moderation_immune": "linksModerationImmune",
  "moderation.auto_moderation.links.punishment": "linksPunishment",
  "permissions.commands": "commandPermissions",
};
