/**
 * Auto-generated User path mapping
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-schema.ts
 */

export interface PathMap {
  [path: string]: {
    field: string;
    children?: string[];
  };
}

export const UserPathMap: PathMap = {
  "level.xp": {
    field: "xp",
  },
  "level.total_xp": {
    field: "totalXp",
  },
  "level.level": {
    field: "level",
  },
  "level.voice_time": {
    field: "voiceTime",
  },
  "level.message_count": {
    field: "messageCount",
  },
  "economy.balance.wallet": {
    field: "wallet",
  },
  "economy.balance.bank": {
    field: "bank",
  },
  "economy.inventory.custom.roles": {
    field: "customRoles",
  },
  "economy.inventory.custom.items": {
    field: "customItems",
  },
  "economy.timeout.work": {
    field: "workTimeout",
  },
  "economy.timeout.timely": {
    field: "timelyTimeout",
  },
  "economy.timeout.daily": {
    field: "dailyTimeout",
  },
  "economy.timeout.weekly": {
    field: "weeklyTimeout",
  },
  "economy.timeout.rob": {
    field: "robTimeout",
  },
  "custom.balance.number": {
    field: "balanceNumber",
  },
  "custom.balance.mode": {
    field: "balanceMode",
  },
  "custom.balance.solid": {
    field: "balanceSolid",
  },
  "custom.balance.url": {
    field: "balanceUrl",
  },
  "custom.profile.bio": {
    field: "profileBio",
  },
  "custom.profile.mode": {
    field: "profileMode",
  },
  "custom.profile.solid": {
    field: "profileSolid",
  },
  "custom.profile.url": {
    field: "profileUrl",
  },
  "custom.profile.color": {
    field: "profileColor",
  },
  "custom.profile.icons": {
    field: "profileIcons",
  },
  "custom.rank.mode": {
    field: "rankMode",
  },
  "custom.rank.solid": {
    field: "rankSolid",
  },
  "custom.rank.url": {
    field: "rankUrl",
  },
  "custom.rank.color": {
    field: "rankColor",
  },
  "custom.level_up.mode": {
    field: "levelupMode",
  },
  "custom.level_up.solid": {
    field: "levelupSolid",
  },
  "custom.level_up.url": {
    field: "levelupUrl",
  },
  "custom.badges": {
    field: "customBadges",
  },
  "temp.games": {
    field: "tempGames",
  },
  "presets.jtc": {
    field: "jtcPresets",
  },
  level: {
    field: "",
    children: ["xp", "total_xp", "level", "voice_time", "message_count"],
  },
  "economy.balance": {
    field: "",
    children: ["wallet", "bank"],
  },
  "economy.inventory.custom": {
    field: "",
    children: ["roles", "items"],
  },
  "economy.timeout": {
    field: "",
    children: ["work", "timely", "daily", "weekly", "rob"],
  },
  custom: {
    field: "",
    children: ["badges"],
  },
  "custom.balance": {
    field: "",
    children: ["number", "mode", "solid", "url"],
  },
  "custom.profile": {
    field: "",
    children: ["bio", "mode", "solid", "url", "color", "icons"],
  },
  "custom.rank": {
    field: "",
    children: ["mode", "solid", "url", "color"],
  },
  "custom.level_up": {
    field: "",
    children: ["mode", "solid", "url"],
  },
  temp: {
    field: "",
    children: ["games"],
  },
  presets: {
    field: "",
    children: ["jtc"],
  },
};

export const UserFieldMap: Record<string, string> = {
  "level.xp": "xp",
  "level.total_xp": "totalXp",
  "level.level": "level",
  "level.voice_time": "voiceTime",
  "level.message_count": "messageCount",
  "economy.balance.wallet": "wallet",
  "economy.balance.bank": "bank",
  "economy.inventory.custom.roles": "customRoles",
  "economy.inventory.custom.items": "customItems",
  "economy.timeout.work": "workTimeout",
  "economy.timeout.timely": "timelyTimeout",
  "economy.timeout.daily": "dailyTimeout",
  "economy.timeout.weekly": "weeklyTimeout",
  "economy.timeout.rob": "robTimeout",
  "custom.balance.number": "balanceNumber",
  "custom.balance.mode": "balanceMode",
  "custom.balance.solid": "balanceSolid",
  "custom.balance.url": "balanceUrl",
  "custom.profile.bio": "profileBio",
  "custom.profile.mode": "profileMode",
  "custom.profile.solid": "profileSolid",
  "custom.profile.url": "profileUrl",
  "custom.profile.color": "profileColor",
  "custom.profile.icons": "profileIcons",
  "custom.rank.mode": "rankMode",
  "custom.rank.solid": "rankSolid",
  "custom.rank.url": "rankUrl",
  "custom.rank.color": "rankColor",
  "custom.level_up.mode": "levelupMode",
  "custom.level_up.solid": "levelupSolid",
  "custom.level_up.url": "levelupUrl",
  "custom.badges": "customBadges",
  "temp.games": "tempGames",
  "presets.jtc": "jtcPresets",
};
